"""initial schema

Revision ID: 564457304bd7
Revises: 
Create Date: 2026-10-09 16:39:16.610608

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '564457304bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_code', sa.String(length=16), nullable=False),
    sa.Column('order_reference', sa.String(length=64), nullable=False),
    sa.Column('expected_sku', sa.String(length=64), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_returns_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_order_reference'), ['order_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_return_code'), ['return_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_returns_status'), ['status'], unique=False)

    op.create_table('expected_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('yolo_class_hints', sa.String(length=256), nullable=False),
    sa.Column('ocr_text_hint', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expected_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_components_return_id'), ['return_id'], unique=False)

    op.create_table('qr_authorizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_agent_id', sa.String(length=36), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_authorizations_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_authorizations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_authorizations_token_hash'), ['token_hash'], unique=True)

    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('qr_auth_id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['qr_auth_id'], ['qr_authorizations.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_return_id'), ['return_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_status'), ['status'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('otp_challenge_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_stored_name', sa.String(length=128), nullable=False),
    sa.Column('image_original_name', sa.String(length=256), nullable=False),
    sa.Column('image_content_type', sa.String(length=64), nullable=False),
    sa.Column('image_size_bytes', sa.Integer(), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['otp_challenge_id'], ['otp_challenges.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_return_id'), ['return_id'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_inspection_id'), ['inspection_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_decisions_return_id'), ['return_id'], unique=False)

    op.create_table('detection_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_path', sa.String(length=256), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inference_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_runs_inspection_id'), ['inspection_id'], unique=True)

    op.create_table('evidence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_records_inspection_id'), ['inspection_id'], unique=True)

    op.create_table('human_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('overrides_automated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_human_reviews_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_human_reviews_return_id'), ['return_id'], unique=False)

    op.create_table('ocr_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('mean_confidence', sa.Float(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_results_inspection_id'), ['inspection_id'], unique=True)

    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_label', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['detection_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_run_id'))

    op.drop_table('detections')
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_results_inspection_id'))

    op.drop_table('ocr_results')
    with op.batch_alter_table('human_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_reviews_return_id'))
        batch_op.drop_index(batch_op.f('ix_human_reviews_inspection_id'))

    op.drop_table('human_reviews')
    with op.batch_alter_table('evidence_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_records_inspection_id'))

    op.drop_table('evidence_records')
    with op.batch_alter_table('detection_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_runs_inspection_id'))

    op.drop_table('detection_runs')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_return_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_inspection_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_return_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_status'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_return_id'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_agent_id'))

    op.drop_table('otp_challenges')
    with op.batch_alter_table('qr_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_authorizations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_qr_authorizations_status'))
        batch_op.drop_index(batch_op.f('ix_qr_authorizations_return_id'))

    op.drop_table('qr_authorizations')
    with op.batch_alter_table('expected_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_components_return_id'))

    op.drop_table('expected_components')
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_status'))
        batch_op.drop_index(batch_op.f('ix_returns_return_code'))
        batch_op.drop_index(batch_op.f('ix_returns_order_reference'))
        batch_op.drop_index(batch_op.f('ix_returns_assigned_agent_id'))

    op.drop_table('returns')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
