"""catalogue, view_type, ai analyses, disposition

Revision ID: 77bbb2bbd6fe
Revises: 564457304bd7
Create Date: 2026-10-09 17:47:21.931591

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '77bbb2bbd6fe'
down_revision = '564457304bd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_components', sa.JSON(), nullable=False),
    sa.Column('identifying_features', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogue_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogue_products_sku'), ['sku'], unique=True)

    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analyses_inspection_id'), ['inspection_id'], unique=True)

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disposition', sa.String(length=24), nullable=True))

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_type', sa.String(length=24), nullable=False))

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogue_product_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_returns_catalogue_product_id'), ['catalogue_product_id'], unique=False)
        batch_op.create_foreign_key(None, 'catalogue_products', ['catalogue_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_returns_catalogue_product_id'))
        batch_op.drop_column('catalogue_product_id')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_column('view_type')

    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_column('disposition')

    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analyses_inspection_id'))

    op.drop_table('ai_analyses')
    with op.batch_alter_table('catalogue_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogue_products_sku'))

    op.drop_table('catalogue_products')
    # ### end Alembic commands ###
